import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import { valid } from '../components/@login'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, toast
}: {
  children: React.ReactNode
  toast: React.ReactNode
}) {
  // const loginSegments = useSelectedLayoutSegment('auth')
  return (
    // const loginSuccessfull = valid()
    // return loginSuccessfull ? toast: login
    <html lang="en">
      <body className={inter.className}>
        {children}
        {toast}
      </body>
    </html>
  )
}
// function useSelectedLayoutSegment(arg0: string) {
//   throw new Error('Function not implemented.')
// }

